### ISSUE TITLE
Compilation error with Elixir 1.10.4

### ISSUE THREAD

**Issue by f0ffee** [membraneframework/shmex#14]
This seems to be the same issue as #10, but doesn't look like it's fixed for Elixir 1.10.4.

```
== Compilation error in file lib/shmex_native.ex ==
** (ArgumentError) could not call Module.delete_attribute/2 because the module Shmex.Native is in read-only mode (@after_compile)
    (elixir 1.10.4) lib/module.ex:2093: Module.assert_not_readonly!/2
    (elixir 1.10.4) lib/module.ex:1285: Module.delete_attribute/2
    (bundlex 0.2.7) lib/bundlex/loader.ex:45: Bundlex.Loader.__after_compile__/2
    (stdlib 3.13.2) lists.erl:1267: :lists.foldl/3
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
```

**Comment by f0ffee** [comment]
My bad, this is fixed when bundlex is bumped up to 0.2.8.
