### ISSUE TITLE
out of date

### ISSUE THREAD

**Issue by ConnorRigby** [membraneframework/shmex#15]
```
     ** (EXIT from #PID<0.3707.0>) an exception was raised:
         ** (Protocol.UndefinedError) protocol Membrane.Payload not implemented for %Shmex{capacity: 12288, guard: #Reference<0.946339676.1657143311.72296>, name: "/shmex-00000028718499235746#000", size: 12288} of type Shmex (a struct). This protocol is implemented for the following type(s): BitString
             (membrane_core 0.6.1) lib/membrane/payload.ex:1: Membrane.Payload.impl_for!/1
             (membrane_core 0.6.1) lib/membrane/payload.ex:32: Membrane.Payload.size/1
             (membrane_core 0.6.1) lib/membrane/buffer/metric/byte_size.ex:15: anonymous fn/2 in Membrane.Buffer.Metric.ByteSize.buffers_size/1
             (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
             (membrane_core 0.6.1) lib/membrane/core/input_buffer.ex:220: Membrane.Core.InputBuffer.do_store_buffers/2
             (membrane_core 0.6.1) lib/membrane/core/input_buffer.ex:148: Membrane.Core.InputBuffer.store/3
             (membrane_core 0.6.1) lib/membrane/core/element/buffer_controller.ex:72: Membrane.Core.Element.BufferController.handle_buffer_pull/3
             (membrane_core 0.6.1) lib/membrane/core/element/message_dispatcher.ex:36: Membrane.Core.Element.MessageDispatcher.handle_message/3
             (stdlib 3.14) gen_server.erl:689: :gen_server.try_dispatch/4
             (stdlib 3.14) gen_server.erl:765: :gen_server.handle_msg/6
             (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3


```

**Comment by mat-hek** [comment]
it seems you didn't include membrane_common_c in deps
